# -*- coding: utf-8 -*-
"""A/B Testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zq3-E7YJX6Bnq7QpFeFJHFcdDvS3BqIQ
"""

import streamlit as st
import polars as pl
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from scipy.stats import norm

import streamlit as st
import polars as pl
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from scipy.stats import norm

# PAGE SETUP & SIDEBAR

st.set_page_config(page_title='A/B Test Analyze', layout='wide')
st.title('📊 A/B Testing: Website Feature CTR')
st.write('This application measures whether a new website feature improved the Click-Through Rate (CTR) using a 2-Sample Z-Test.')

# Sidebar for interactive business thresholds
st.sidebar.header('⚙️ Test Parameters')
alpha = st.sidebar.slider('Significance Level (Alpha)',min_value=0.01,max_value=0.10,value=0.05,step=0.01,help='Probability of a Type 1 error (false positive)')
delta = st.sidebar.slider('Minimum Detectable Effect (MDE)',min_value=0.01,max_value=0.15,value=0.05,step=0.01,help='The minimum business threshold required to launch the feature')

# STEP 1: GENERATE MOCK DATA
@st.cache_data
def generate_mock_data():
  np.random.seed(42)
  data_size = 2000
  mock_data = {
      'IP Address':[f'user_{i}' for i in np.random.randint(1,1500,data_size)],
      'LoggedInFlag': np.random.choice([0,1],data_size),
      'ServerID': np.random.choice([1,2,3],data_size),
      'VisitPageFlag': [np.random.choice([0,1], p=[0.8,0.2]) if s == 1 else np.random.choice([0,1],p=[0.88,0.12]) for s in np.random.choice([1,2,3], data_size)]
  }
  return pl.DataFrame(mock_data)

df_raw = generate_mock_data()


# STEP 2: DATA PREPARTION
# Group by user and sum visits

df_grouped = (
    df_raw.group_by(['IP Address','LoggedInFlag','ServerID'])
    .agg(pl.col('VisitPageFlag').sum().alias('VisitPageFlagSum'))
)

df = (
    df_grouped.with_columns([
        pl.when(pl.col('VisitPageFlagSum') > 0).then(1).otherwise(0).alias('click'),
        pl.when(pl.col('ServerID')==1).then(pl.lit('exp')).otherwise(pl.lit('con')).alias('group')
    ])
    .rename({'IP Address':'user_id','LoggedInFlag':'has_account'})
    .drop(['ServerID','VisitPageFlagSum'])
)

# STEP 3. CALCULATE CTR & METRICS

# Filter into control and experiment DataFrames
con_df = df.filter(pl.col('group') == 'con')
exp_df = df.filter(pl.col('group')== 'exp')

# Count users
N_con = con_df.height
N_exp = exp_df.height

# Sum clicks
X_con = con_df.select(pl.col('click').sum()).item()
X_exp = exp_df.select(pl.col('click').sum()).item()

# Calculate CTRs
p_con_hat = X_con / N_con
p_exp_hat = X_exp / N_exp

st.header('1. High-Level Metrics')
col1,col2,col3 = st.columns(3)
col1.metric('Total users', f'{N_con + N_exp:,}')
col2.metric('Control CTR',f'{p_con_hat:.2%}')
col3.metric('Experiment CTR', f'{p_exp_hat:.2%}', delta=f'{(p_exp_hat - p_con_hat):.2%}')

# STEP 4: VISUALIZATING CLICK DISTRIBUTIONS
st.header('2. Click Distribution')

# To plot easily with Ploty, I aggregated the count first
counts = df.group_by(['group','click']).len().to_pandas()
counts['click'] = counts['click'].replace({0: 'No Clicks', 1:'Clicked'})

fig_clicks = px.bar(
    counts,
    x='group',
    y='len',
    color='click',
    barmode='group',
    labels={'len':'User Count','group':'Test Group','click':'User Action'},
    color_discrete_sequence=['mediumseagreen', 'lightslategray'] # Changed from 'Viridis_r'
)
st.plotly_chart(fig_clicks,use_container_width=True)


# STEP 5: 2-SAMPLE Z-TEST & P-VALUE
p_pooled_hat = (X_con + X_exp) / (N_con + N_exp)
pooled_variance = p_pooled_hat * (1-p_pooled_hat) * (1/N_con + 1/N_exp)
SE = np.sqrt(pooled_variance)

Test_stat = (p_exp_hat - p_con_hat) / SE
Z_crit = norm.ppf(1 - alpha/2)
p_value = 2 * norm.sf(abs(Test_stat))

st.header('3. Statistical Significance')
st.write(f'**P-value:** `{p_value:.4f}`')

if p_value <= alpha:
  st.success(f'**Statistically Significant:** The p-value is lower than our alpha threshold ({alpha}). The difference is unlikely du to random chance.')
else:
  st.error(f'**NOt Statistically Significant:** The p-value is higher than our alpha threshold ({alpha}). The difference could be random.')


# STEP 6: PLOTTING THE NORMAL CURVE
st.subheader('Standard Normal Curve Visualization')
mu,sigma = 0,1
x_vals = np.linspace(mu -4*sigma, mu +4*sigma, 500)
y_vals = norm.pdf(x_vals, mu, sigma)

fig2 = go.Figure()
fig2.add_trace(go.Scatter(x=x_vals,y=y_vals,mode='lines',name='Normal Distribution',line=dict(color='black')))

# Shade in the right rejection region
x_fill_right = np.linspace(Z_crit, mu + 4*sigma,100)
fig2.add_trace(
    go.Scatter(
        x=np.concatenate([[Z_crit], x_fill_right, [mu+4*sigma]]),
        y=np.concatenate([[0], norm.pdf(x_fill_right,mu,sigma), [0]]),
        fill='toself', fillcolor='rgba(255,0,0,0.3)', line=dict(width=0),
        name='Rejection Region', showlegend=False
    ))

# Shade the left rejection region
x_fill_left = np.linspace(mu- 4*sigma, -Z_crit, 100)
fig2.add_trace(go.Scatter(x=np.concatenate([[mu - 4*sigma], x_fill_left, [-Z_crit]]),
                          y=np.concatenate([[0], norm.pdf(x_fill_left, mu, sigma), [0]]),
                          fill='toself', fillcolor='rgba(255, 0, 0, 0.3)', line=dict(width=0),
                          showlegend=False))

# Add markers for statistics
fig2.add_vline(x=Test_stat, line_dash="dash", line_color="green", annotation_text=f"Test Stat: {Test_stat:.2f}")
fig2.add_vline(x=Z_crit, line_dash="dot", line_color="blue", annotation_text=f"Z-crit: {Z_crit:.2f}")
fig2.add_vline(x=-Z_crit, line_dash="dot", line_color="blue")

fig2.update_layout(xaxis_title="Z-value", yaxis_title="Probability Density", margin=dict(t=30))
st.plotly_chart(fig2, use_container_width=True)

# STEP 7: CONFIDENCE INTERVAL & PRACTICAL SIGNIFIANCE
st.header('4. Practical (Business) Signifiance')
CI_lower = (p_exp_hat - p_con_hat) - Z_crit * SE
CI_upper = (p_exp_hat - p_con_hat) + Z_crit * SE

st.write(f'**Confidence Interval:**We are {(1-alpha)*100:.0f}% confident that the true difference in CTR lies between `{CI_lower:.3f}`.')

if CI_lower >= delta:
  st.success(f'**Practically Significant:** The lower bound of our Confidence Interval ({CI_lower:.3f}) is greater than our Minimum Detectable Effect ({delta}). This feature meets the business requirements for launch!')
else:
  st.warning(f'**Not Practically Significant:** The lower bound of our Confidence Interval ({CI_lower:.3f}) does not confidently exceed our Minimum Detectable Effect ({delta}). The effect size may be too small to jusitfy the business cost.')