# -*- coding: utf-8 -*-
"""EV_Charging_A/B_Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ti3PtFu40cS5TLo76y99w0m8LwHof8y6
"""

import streamlit as st
import pandas as pd
import numpy as np
from scipy.stats import ttest_ind


st.set_page_config(page_title='EV Charging App A/B Test', layout='wide')

st.title('⚡ EV Charging Mobile App: A/B Testing Dashboard')
st.markdown("""
This dashboard analyzes the impact of our new **Smart Off-Peak Charging Notifications** feature.
We are checking if the push alerts successfully drive higher energy consumption and app engagement.
""")

#--- Sidebar Controls ---
st.sidebar.header('Simulation Settings')
sample_size = st.sidebar.slider('Number of Users per Group', min_value=100, max_value=5000,value=1000,step=100)
random_seed = st.sidebar.number_input('Random Seed', value=42)

#--- Step 1: Data Generation ---
@st.cache_data
def generate_ev_data(n_users,seed):
  np.random.seed(seed)
  user_ids = np.arange(n_users * 2)
  groups = np.array(['Control'] * n_users + ['Test'] * n_users)

  # Energy Delivered per user per month (kWh)
  # Test group sees higher average charging due to alerts
  energy_control = np.random.normal(120,25,n_users)
  energy_test = np.random.normal(135,25,n_users)
  energy = np.concatenate([energy_control, energy_test])

  # Session Revenue (€ per user per month)
  # Test group has slightly lower or equal revenue per kWh due to discounts, but higher volume
  rev_control = np.random.normal(45,10,n_users)
  rev_test = np.random.normal(48,10,n_users)
  revenue = np.concatenate([rev_control, rev_test])

  # App Engagement (Weekly App Opens)
  # Test group opens the app more frequently due to push notifications
  opens_control = np.random.normal(5,1.5,n_users)
  opens_test = np.random.normal(7,1.5,n_users)
  opens = np.concatenate([opens_control, opens_test])


  df_product = pd.DataFrame({
      'User ID': user_ids,
      'Group': groups,
      'Energy Delivered (kWh)': np.clip(energy,0,None),
      'Monthly Revenue (€)': np.clip(revenue,0,None),
      'Weekly App Opens': np.clip(opens,0,None)
  })
  return df_product

df_clean = generate_ev_data(sample_size,random_seed)

tab1,tab2 = st.tabs(['📊 Dataset Exploration','🔬 Statistical Hypothesis Testing'])

with tab1:
  st.header('Mock User Data Overview')
  st.write('Here is a sample of the generated data matching an EV charging ecosystem:')
  st.dataframe(df_clean.head(10),use_container_width=True)

  st.subheader('Group Summary Statistics')
  summary = df_clean.groupby('Group').mean().drop(columns=['User ID'])

with tab2:
  st.header('Two-Sample T-Test Results')
  st.markdown('We evaluate our metrics using an alpha level ($\\alpha$) of **0.05**.')

  control = df_clean[df_clean['Group'] == 'Control']
  test = df_clean[df_clean['Group'] == 'Test']

  metrics = {
      'Energy Delivered (KWh)':'Energy Delivered (kWh)',
      'Monthly Revenue (€)':'Monthly Revenue (€)',
      'Weekly App Opens': 'Weekly App Opens'
  }

  for label, col in metrics.items():
    st.subheader(f'Analysis for: {label}')

    # Calculate T-test
    t_stat, p_val = ttest_ind(control[col], test[col], equal_var=False)

    col1,col2 = st.columns(2)
    col1.metric('T-Statistic', f'{t_stat:.4f}')
    col2.metric('P-Value',f'{p_val:.5f}')

    # Decision Logic
    if p_val < 0.05:
      st.success('✅ **Statistically Significant Change!** The difference in {label} between groups is unlikely to be random noise.')
      diff = test[col].mean() - control[col].mean()
      if diff > 0:
        st.info(f'The Test group outperformed the Control group by an average of **{diff:.2f}** units.')
      else:
          st.warning(f'The Test group performed worse than the Control group by an average of **{abs(diff):.2f}** units')
    else:
      st.error(f'❌ **Not Statistically Significant.** We fail to reject the null hypothesis for {label}.')
    st.divider()