# -*- coding: utf-8 -*-
"""EV_Charging_App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YWMJV8XJwdlCVabC3NCjUunatAWXlwMZ
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import math
from scipy import stats
from statsmodels.stats.proportion import proportions_ztest
from statsmodels.stats.power import NormalIndPower

@st.cache_data
def generate_mock_data(n_users=3000):
  """
    Generates mock data for an EV Charging App in Western Europe.
    The variant group will have a slightly better performance to simulate a successful A/B test.
  """
  np.random.seed(42)

  countries = np.random.choice(['France','Netherlands','United Kingdom','Norway'],n_users,p=[0.3,0.4,0.2,0.1])
  personas = np.random.choice(['Casual','Commuter','Fleet Driver'],n_users,p=[0.5,0.4,0.1])
  groups = np.random.choice(['Control','Variant'],n_users,p=[0.5,0.5])

  df_ev = pd.DataFrame({
      'user_id': range(1,n_users + 1),
      'country': countries,
      'persona': personas,
      'group': groups
  })

  # Generate metrics with a slight uplift for the Variant group
  # Metric 1: Charging sessions per week (Continuous data)
  base_sessions = np.random.normal(loc=2.5,scale=1.0,size=n_users)
  variant_uplift_sessions = np.where(df_ev['group'] == 'Variant',0.4,0.0)

  # Add a country specific bias (e.g., Netherlands charges more frequently)
  country_bias = np.where(df_ev['country']=='Variant',0.5,0.0)

  df_ev['sessions_per_week'] = np.maximum(0,np.round(base_sessions + variant_uplift_sessions + country_bias, 1))

  # Metric 2: Premium Subscription Conversion (Binary data 0 or 1)
  # Control conversion rate ~ 12%, Variant ~ 15%
  base_prob = 0.12
  variant_prob = 0.15
  probabilities = np.where(df_ev['group']=='Control',base_prob,variant_prob)
  df_ev['converted_to_premium'] = np.random.binomial(1,probabilities)

  return df_ev

# Statistical Functions
def calculate_significance_means(control_data, variant_data):
  'Performas a T-test for continuous variables (e.g. sessiosn per week)'
  t_stat, p_val = stats.ttest_ind(control_data,variant_data,equal_var=False)
  return t_stat,p_val

def calculate_significance_proportions(control_conv,control_total,variant_conv,variant_total):
  'Performs a Z-test for binary proportions (e.g., conversion rates).'
  counts =  np.array([variant_conv, control_conv])
  nobs = np.array([variant_total, control_total])
  z_stat, p_val = proportions_ztest(counts,nobs)
  return z_stat,p_val

def calculate_mde(baseline_rate,sample_size_per_group,power=0.8,alpha=0.05):
  'Calculate Minimum Detectable Effect using statsmodels'
  analysis = NormalIndPower()
  effect_size = analysis.solve_power(
      effect_size=None,
      power=power,
      alpha=alpha,
      nobs1=sample_size_per_group,
      ratio=1.0 # 50/50 split
  )

  # Convert Cohen's h back to p2 (approximation for proportion MDE)
  p1 = baseline_rate
  p2_asin = math.asin(math.sqrt(p1)) + (effect_size / 2)
  p2 = math.sin(p2_asin) ** 2

  absolute_mde = (p2-p1)
  relative_mde = absolute_mde / p1
  return absolute_mde, relative_mde


# STREAMIT UI & PAGES
st.set_page_config(page_title='EV Product Analytics Hub',layout='wide')

df_ev = generate_mock_data()

# Sidebar Navigation
st.sidebar.title('Navigation')
page = st.sidebar.radio('Select a Tool:',['A/B Test Analyzer','Customer Segmentation','Power & MDE Calculator'])

st.sidebar.markdown('---')
st.sidebar.info('🚙 **Context:** EV Charging App evaluating a new Smart Route feature.')

if page == 'A/B Test Analyzer':
  st.title('🧪 A/B Test Analyzer')

  st.write('Analyze the results of our Smart Route experiment to see if it significantly impacted user behavior.')

  st.subheader('1. Premium Subscription Conversion (Z-Test)')
  # Calculate totals and conversions
  control_mask = df_ev['group'] == 'Control'
  variant_mask = df_ev['group'] == 'Variant'

  ctrl_total = control_mask.sum()
  var_total = variant_mask.sum()
  ctrl_conv = df_ev[control_mask]['converted_to_premium'].sum()
  var_conv = df_ev[variant_mask]['converted_to_premium'].sum()

  ctrl_rate = ctrl_conv / ctrl_total
  var_rate = var_conv / var_total

  col1,col2,col3 = st.columns(3)
  col1.metric('Control Conversion',f'{ctrl_rate:.2%}')
  col2.metric('Variant Conversion',f'{var_rate:.2%}',f'{(var_rate - ctrl_rate):.2%} absolute diff')

  # Statistical Test
  z_stat, p_val_z = calculate_significance_proportions(ctrl_conv,ctrl_total,var_conv,var_total)
  is_sig_z = p_val_z < 0.05

  col3.metric('Statistically Significant ?','Yes ✅' if is_sig_z else 'No ❌',f'p-value: {p_val_z:.4f}')

  st.subheader('2. Weekly Charging Sessions (T-Test)')
  ctrl_mean = df_ev[control_mask]['sessions_per_week'].mean()
  var_mean = df_ev[variant_mask]['sessions_per_week'].mean()

  col1,col2,col3 = st.columns(3)
  col1.metric('Control Avg Sessions',f'{ctrl_mean:.2f}')
  col2.metric('Variant Avg Sessions',f'{var_mean:.2f}',f'{(var_mean - ctrl_mean):.2f} diff')

  t_stat, p_val_t = calculate_significance_means(df_ev[control_mask]['sessions_per_week'],df_ev[variant_mask]['sessions_per_week'])
  is_sig_t = p_val_t < 0.05

  col3.metric('Statistically Significant?','Yes ✅' if is_sig_t else 'No ❌',f'p-value:{p_val_t:.4f}')

  fig = px.box(
      df_ev,
      x='group',
      y='sessions_per_week',
      color='group',
      title='Distribution of Charging Sessions by Group',
      color_discrete_sequence=['#1f77b4','#ff7f0e']
  )
  st.plotly_chart(
      fig,
      use_container_width=True
  )
elif page == 'Customer Segmentation':
  st.title('👥 Customer Segmentation Analysis')
  st.write('Does the new feature work better for specific regions or user personas?')

  segment_by = st.selectbox('Select Segment Attribute:', ['country','persona'])

  # Group Data
  seg_df = df_ev.groupby([segment_by, 'group'])['converted_to_premium'].mean().reset_index()
  seg_df['converted_to_premium'] = seg_df['converted_to_premium'] * 100

  # Plotly Bar Chart
  fig = px.bar(
      seg_df,
      x=segment_by,
      y='converted_to_premium',
      color='group',
      barmode='group',
      title=f'Premium Converted Rate by {segment_by.capitalize()}',
      color_discrete_sequence=['#1f77b4','#ff7f0e']
  )
  st.plotly_chart(fig,user_container_width=True)

  st.info('💡 **Analyst Tip:** Look for segments where the Variant severly underperforms the Control. This helps PMs decide if a feature should be rolled out globally or only to specific segments.')


elif page == 'Power & MDE Calculator':
  st.title('⚡ Power & MDE Calculator')
  st.write('Help your Product Managers plan experiments. Calculate the Minimum Detectable Effect (MDE) to set expectations on what uplift is realistic to measure.')

  col1,col2 = st.columns(2)
  with col1:
    baseline_conv = st.number_input('Baseline Conversion Rate (%)',min_value=1.0,max_value=99.0,value=12.0) / 100
    sample_size = st.number_input('Sample Size (per group)',min_value=100,max_value=500000,value=5000,step=500)
  with col2:
    power_input = st.slider('Statistical Power (1 - Beta)',min_value=0.5,max_value=0.99, value=0.80)
    alpha_input = st.selectbox('Significant Level (Alpha)',[0.01,0.05,0.10],index=1)

  if st.button('Calculate MDE'):
    abs_mde,rel_mde = calculate_mde(baseline_conv, sample_size, power=power_input,alpha=alpha_input)

    st.success(f'**Results:** To reach statistical significance with {sample_size} users per group, your new feature needs to generate at least a: ')

    c1,c2 = st.columns(2)
    c1.metric('Relative MDE',f'{rel_mde:.2%}')
    c2.metric('Absolute MDE',f'{abs_mde:.2%}')

    st.write(f'This means your conversion rate needs to jump from **{baseline_conv:.2%}** to **{baseline_conv + abs_mde}')