# -*- coding: utf-8 -*-
"""EV_Market_Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17PNVs_PvCd2weg4bjF2IolBnpnfC840N
"""

import streamlit as st
import polars as pl
import plotly.express as px

st.set_page_config(page_title='Ev Market Dashboard',layout='wide',page_icon='⚡')
st.title('⚡ Global EV Market Intelligence')
st.markdown('Analyze the relationship between EV sales, charging infrastructure, and market drivers.')

@st.cache_data
def load_data():
  df_ev = pl.read_csv('master_ev_data.csv')
  df_ev = df_ev.with_columns(pl.date(pl.col('year'),pl.col('month'),1).alias('date'))
  return df_ev

try:
  df_ev = load_data()

  # -- Sidebar Filters --
  st.sidebar.header('🔍 Global Filters')

  # Get a list of countries, dropping any nulls just in case
  countries = df_ev['country'].drop_nulls().unique().to_list()

  # Let the user selct a country (Default to France if it exists)
  select_country = st.sidebar.selectbox('Select Country:', countries)

  # Filter the dataframe using Polars
  filtered_df = df_ev.filter(pl.col('country') == select_country)

  # --- KPI Metrics Row ---
  st.subheader(f'Market Snapshot: {select_country}')

  # Calculcate some quick metrics to show at the top
  latest_data = filtered_df.sort('date',descending=True).row(0,named=True)
  total_sales_all_time = filtered_df['total_units_sold'].sum()

  col_kpi1, col_kpi2, col_kpi3 = st.columns(3)
  col_kpi1.metric('All-Time EV Units Sold',f'{total_sales_all_time:,.0f}')
  if latest_data.get('total_chargers_cumulative') is not None:
    col_kpi2.metric('Total Public Chargers (Latest)',f'{latest_data['total_chargers_cumulative']:,.0f}')
  if latest_data.get('gasoline_price_usd_per_liter') is not None:
    col_kpi3.metric('Current Cas Price (USD/L)', f'${latest_data['gasoline_price_usd_per_liter']:.2f}')

  st.divider()

  # --- Charts Row 1 ---
  col1,col2 = st.columns(2)
  chart1_df = filtered_df.drop_nulls(subset=['total_chargers_cumulative','total_units_sold'])

  with col1:
    st.markdown('**Monthly EV Sales vs. Charging Infrastructure**')

    fig1 = px.scatter(
        chart1_df.to_pandas(),
        x='date',
        y='total_units_sold',
        size='total_chargers_cumulative',
        color='total_units_sold',
        hover_data=['slow_chargers_cumulative','fast_chargers_cumulative'],
        labels={'total_units_sold':'Units Sold','date':'Date'}
    )
    st.plotly_chart(fig1,use_container_width=True)

  with col2:
    st.markdown('***Does Gas Prices Affect Sales?**')
    fig2 = px.scatter(
        filtered_df.to_pandas(),
        x='gasoline_price_usd_per_liter',
        y='total_units_sold',
        color='date',
        trendline='ols',
        labels={'gasoline_price_usd_per_liter':'Gas Price (USD/L)','total_units_sold':'EVs Sold'}
    )
    st.plotly_chart(fig2,use_container_width=True)

  # --- Chart Row 2 ---
  st.markdown('**Consumer Interest: Google Search Trends**')
  desired_trend_cols = ["trend_tesla", "trend_byd", "trend_electric_car", "trend_ev_charging"]
  actual_trend_cols = [col for col in desired_trend_cols if col in filtered_df.columns]

  if len(actual_trend_cols) > 0:
    fig3 = px.line(
    filtered_df.to_pandas(),
    x="date",
    y=actual_trend_cols,
    labels={"value": "Search Trend Score", "variable": "Search Term", "date": "Date"}
    )
    st.plotly_chart(fig3, use_container_width=True)
  else:
        st.info("No search trend data available for this country.")

# --- Raw Data Expander ---
  with st.expander('View Underlying Data'):
    st.dataframe(filtered_df.to_pandas(),use_container_width=True)

except Exception as e:
  st.error(f'An error occured: {e}. Please ensure master_ev_data.csv exists and is formatted correctly.')