# -*- coding: utf-8 -*-
"""product_calculator_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xxxV8oKJp_676SKMWjyOQznEKxapfwnI
"""

import streamlit as st

def calculate_conversion_rate(visitors, conversions):
  visitors = max(abs(visitors),1)
  conversions = abs(conversions)
  return round((conversions / visitors) * 100,2)

def calculate_churn_rate(start_customers, lost_customers):
  start_customers = max(abs(start_customers),1)
  lost_customers = abs(lost_customers)
  return round((lost_customers / start_customers) * 100,2)

def calculate_cac(marketing_spend,new_customers):
  marketing_spend = abs(marketing_spend)
  new_customers = max(abs(new_customers),1)
  return round(marketing_spend / new_customers,2)


#--- STREAMLIT UI ---
st.title('📊 Product Metrics Calculator')
st.write('Welcome! Choose a metric to calculate below.')

choice = st.selectbox(
    'Select a Metric',
    ('Conversion Rate','Churn Rate','Customer Acquisition Cost (CAC)')
)

if choice == 'Conversion Rate':
  visitors = st.number_input('Total Visitors',min_value=0,value=100)
  conversions = st.number_input('Total Conversions',min_value=0,value=5)

  if st.button('Calculate'):
    result = calculate_conversion_rate(visitors, conversions)
    st.success(f'The Conversion Rate is: {result}%')

elif choice == 'Churn Rate':
  start_customers = st.number_input('Customers at the Start of Period',min_value=0,value=1000)
  lost_customers = st.number_input('Customers Lost in Peroid',min_value=0,value=50)

  if st.button('Calculate'):
    result = calculate_churn_rate(start_customers, lost_customers)
    st.success(f'The Churn Rate is: {result}%')

elif choice == 'Customer Acquisition Cost (CAC)':
  spend = st.number_input('Total Marketing & Sales Spend (€)', min_value=0.0, value=5000.0)
  new_cust = st.number_input('New Customers Acquired',min_value=0.0, value=100.0)

  if st.button('Calculate'):
    result = calculate_cac(spend, new_cust)
    st.success(f'The Customer Acquisition Cost is: €{result}')