# -*- coding: utf-8 -*-
"""Online_Retail_Product_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uTGdNU7j4Kk_sUPKe4bh-7pm0hIIVGMa
"""

import numpy as np
import polars as pl
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import gdown as gd
from scipy import stats
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, roc_auc_score
from sklearn.linear_model import LinearRegression

"""# **1. Loading the dataset using gdown (to download from my google cloud storage), then convert to Polarzs**"""

url = 'https://drive.google.com/uc?id=1cslllX4ga7Ud-YoUtozMcgcmLhusvvL8'
gd.download(url,'online_retail_2009_2011.csv',quiet=True)

df_online_retail = pl.read_csv(
    'online_retail_2009_2011.csv',
    infer_schema_length=10000,
    schema_overrides={'Invoice': pl.Utf8}
)

display(df_online_retail.head())

print(f'Raw dataset shape: {df_online_retail.height:,} rows | {df_online_retail.width} columns')

"""# **Phase 1: Data Cleaning**"""

df_product_clean = (
    df_online_retail
    .filter(pl.col('Customer ID').is_not_null())
    .filter(~pl.col('Invoice').cast(pl.Utf8).str.starts_with('C'))
    .filter(pl.col('Quantity') > 0)
    .filter(pl.col('Price') >0)
    .with_columns(
        pl.col('Customer ID').cast(pl.Int64).cast(pl.Utf8).alias('CustomerID'),
        (pl.col('Quantity') * pl.col('Price')).alias('Revenue'),
        # First, parse InvoiceDate to a Datetime type, correcting format and handling errors
        pl.col('InvoiceDate').str.strptime(pl.Datetime, format='%m/%d/%y %H:%M', strict=False).alias('ParsedInvoiceDate')
    )
    .with_columns(
        pl.col('ParsedInvoiceDate').dt.strftime('%Y-%m').alias('YearMonth'),
        pl.col('ParsedInvoiceDate').dt.date().alias('OrderDate')
    )
    .drop(['CustomerID', 'ParsedInvoiceDate'])
)

print(f'Cleaned dataset shape: {df_product_clean.height:,} rows | {df_product_clean.width} columns')
display(df_product_clean.head(5))

"""# **Phase 2: Deep-Dive Behavioral & Funnel Analysis**"""

# Data Aggregation & Monthly KPI's: aggregate total revenue and active customers by country
country_kpis = (
    df_product_clean
    .group_by('Country')
    .agg(
        pl.col('Revenue').sum().round(2).alias('Total_Revenue'),
        pl.col('Customer ID').n_unique().alias('Active_Customers'),
        pl.col('Invoice').n_unique().alias('Total_Orders')
    )
    .sort('Total_Revenue',descending=True)
    .head(10)
)

fig_monthly_kpi = px.bar(
    country_kpis.to_pandas(),
    x='Country',
    y='Total_Revenue',
    title='Top 10 Markets by Total Revenue (£)',
    text_auto='.2s',
    color='Total_Revenue',
    labels={'Total_Revenue':'Total Revenue (Pounds)'}
)

fig_monthly_kpi.show()

# Cohort Retention Matrix: We assign each user to an acquisition cohort based on their first purchase month, then track their retention over subsequent months.

# 1. Finding the first purchase
first_purchase = (
    df_product_clean
    .group_by('Customer ID')
    .agg(pl.col('OrderDate').min().dt.strftime('%Y-%m').alias('CohortMonth'))
)

# 2. Join back to calculate month index
retention_data = (
    df_product_clean
    .join(first_purchase, on='Customer ID',how='left')
    .group_by(['CohortMonth','YearMonth'])
    .agg(pl.col('Customer ID').n_unique().alias('ActiveUsers'))
    .sort(['CohortMonth','YearMonth'])
)

# Convert to Pandas to build the pivot matrix for Plotly
ret_pd = retention_data.to_pandas()
ret_pd['CohortDate'] = pd.to_datetime(ret_pd['CohortMonth'])
ret_pd['ActivityDate'] = pd.to_datetime(ret_pd['YearMonth'])
ret_pd['CohortIndex'] = ((ret_pd['ActivityDate'].dt.year - ret_pd['CohortDate'].dt.year) * 12 +
                         (ret_pd['ActivityDate'].dt.month - ret_pd['CohortDate'].dt.month))

cohort_matrix = ret_pd.pivot_table(index='CohortMonth',columns='CohortIndex',values='ActiveUsers')
cohort_size = cohort_matrix.iloc[:, 0]
retention_matrix = cohort_matrix.divide(cohort_size, axis=0) * 100

fig_cohort_retention = px.imshow(
    retention_matrix.round(1),
    labels=dict(x='Months Since Acquisition',y='Cohort Month',color='Retention (%)'),
    title='Customer Retention Cohort Matrix (%)',
    text_auto=True,
    color_continuous_scale='viridis'
)

fig_cohort_retention.update_layout(height=600,width=900)
fig_cohort_retention.show()

"""# **3. Multi-Touch Attribution & Pathing (Cross-Category Discovery)**"""

# Since retail transactions lack digital marketing ad clicks, Product Analysts map product discovery paths—tracking which item category a customer buys first versus what they buy second.

pathing_df = (
    df_product_clean
    .with_columns(pl.col('StockCode').cast(pl.Utf8).str.slice(0,3).alias('Category'))
    .sort(['Customer ID','InvoiceDate'])
    # Using window functions to get the next category bought by the same user
    .with_columns(
        pl.col('Category').shift(-1).over('Customer ID').alias('Next_Category'),
        pl.col('Invoice').shift(-1).over('Customer ID').alias('Next_Invoice')
    )
    # Only keep transitiohns between distinct orders
    .filter(pl.col('Invoice') != pl.col('Next_Invoice'))
    .filter(pl.col('Next_Category').is_not_null())
    .group_by(['Category','Next_Category'])
    .agg(pl.col('Customer ID').n_unique().alias('Transitions'))
    .sort('Transitions',descending=True)
    .head(15)
)

path_pd = pathing_df.to_pandas()
all_nodes = list(set(path_pd['Category']).union(set(path_pd['Category']).union(set(path_pd['Next_Category']))))
node_dict = {node: i for i, node in enumerate(all_nodes)}

fig_path = go.Figure(data=[go.Sankey(
    node = dict(label = all_nodes, pad = 15,thickness = 20, color = 'royalblue'),
    link = dict(
        source = [node_dict[src] for src in path_pd['Category']],
        target = [node_dict[tgt] for tgt in path_pd['Next_Category']],
        value = path_pd['Transitions']
    )
)])
fig_path.update_layout(title_text='Top 15 Cross-Category Purchase Paths (1st Order -> 2nd Order)',font_size=12)
fig_path.show()

"""# **4. Time-to-Event Analysis (Repeat Buyer Aha! Moment)**"""

# We calculate how many days it takes a new customer to return for their second purchase.

# Get the distinct order dates per customer
order_dates = (
    df_product_clean
    .select(['Customer ID','OrderDate','Invoice'])
    .unique(subset=['Customer ID','Invoice'])
    .sort(['Customer ID','Invoice'])
    .with_columns(
        pl.col('OrderDate').shift(-1).over('Customer ID').alias('Next_OrderDate'),
        # Calculate order sequence number per user
        pl.col('OrderDate').rank('dense').over('Customer ID').alias('OrderRank')
    )
    .filter(pl.col('OrderRank')==1) # Focus on time between 1st and 2nd purchase
    .filter(pl.col('Next_OrderDate').is_not_null())
    .with_columns(
        ((pl.col('Next_OrderDate') - pl.col('OrderDate')).dt.total_days()).alias('Days_to_Second_Purchase')
    )
)

fig_time_to_event = px.histogram(
    order_dates.to_pandas(),
    x='Days_to_Second_Purchase',
    nbins=50,
    range_x=[0,180],
    title='Time-to-Event: Days Between 1st and 2nd Purchases',
    labels={'Days_to_Second_Purchase':'Days to 2nd Purchase'},
    color_discrete_sequence=[px.colors.sequential.Viridis_r[0]]
)

fig_time_to_event.add_vline(
    x=order_dates['Days_to_Second_Purchase'].median(),
    line_dash='dash',
    line_color='red',
    annotation_text=f'Median: {order_dates["Days_to_Second_Purchase"].median():.1f} days'
)

fig_time_to_event.show()

"""# **Phase 3: A/B Testing & Statistical Rigor**"""

orders_df = (
    df_product_clean
    .group_by(['Customer ID','Invoice'])
    .agg(pl.col('Revenue').sum().alias('OrderValue'))
    .with_columns(
        # Assign Control (A) or Treatment (B) deterministically based on odd/even Customer ID
        pl.when(pl.col('Customer ID').cast(pl.Int64) % 2 == 0)
        .then(pl.lit('Control')) # Added .then() for the true condition
        .otherwise(pl.lit('Treatment'))
        .alias('ExperimentGroup')

    )
)

np.random.seed(42)
orders_pd = orders_df.to_pandas() # Changed order_df to orders_df to match the DataFrame name
treatment_mask = order_pd['ExperimentGroup'] == 'Treatment'
order_pd.loc[treatment_mask, 'OrderValue']*= np.random.normal(1.05,0.1,size=treatment_mask.sum())

"""# **1. Sample Ratio Mismatch (SRM) Test**"""

# Before checking revenue, we must run a Chi-Square ($\chi^2$) test to verify traffic was routed evenly without systemic tracking bugs.

group_counts = orders_pd['ExperimentGroup'].value_counts()
observed = [group_counts['Control'], group_counts['Treatment']]
expected = [len(orders_pd) / 2, len(orders_pd) / 2] # Corrected: len(order_pd) is divided by 2, not the DataFrame itself.

chi2_stat, p_val_srm = stats.chisquare(f_obs=observed,f_exp=expected)

print('--- Sample Ration Mismatch (SRM) Check ---')
print(f'Observed: Control={observed[0]:,}, Treatment={observed[1]:,}')
print(f'Chi-Square Stat: {chi2_stat:.4f} | p-value: {p_val_srm:.4f}')
if p_val_srm < 0.01:
  print('WARNING: Statistically significant SRM detected! Do not trust test metrics.')
else:
  print('SUCCESS: Traffic split is balanced. Proceed to hypothesis testing.')

"""# **2. Hypothesis Testing ($t$-test & Mann-Whitney U)**"""

# We test whether the difference in means is statistically significant.

control_rev = orders_pd[orders_pd['ExperimentGroup']== 'Control']['OrderValue']
treatment_rev = orders_pd[order_pd['ExperimentGroup']== 'Treatment']['OrderValue']

# Two-Sample t-test
t_stat, p_val_t = stats.ttest_ind(treatment_rev,control_rev,equal_var=False)

# Non-parametric Mann-Whitney U test
u_stat, p_val_u  = stats.mannwhitneyu(treatment_rev, control_rev, alternative='two-sided')

print("\n--- Hypothesis Testing Results ---")
print(f"Control Mean: £{control_rev.mean():.2f} | Treatment Mean: £{treatment_rev.mean():.2f}")
print(f"Absolute Lift: £{treatment_rev.mean() - control_rev.mean():.2f} ({(treatment_rev.mean()/control_rev.mean() - 1)*100:.2f}%)")
print(f"Welch's t-test p-value: {p_val_t:.5f}")
print(f"Mann-Whitney U p-value: {p_val_u:.5f}")

"""# **3. Variance Reduction: CUPED**

- CUPED (Controlled Experiments Using Pre-Experiment Data) uses a user's pre-experiment spend ($X$) as a covariate to shrink the variance of post-experiment spend ($Y$), allowing you to detect smaller lifts with greater statistical power.

- The adjusted metric is calculated as:


```
Ycuped = Y - 0(X-X)
```



```
where 0 = Cov(X,Y)/Var(x)
```


"""

# # Simulate pre-experiment baseline spend (X) correlated with experiment spend (Y)
orders_pd['Pre_Experiment_Spend'] = orders_pd['OrderValue'] * np.random.normal(0.8,0.2, size=len(orders_pd)) + np.random.normal(10,5,size=len(orders_pd))

X = orders_pd['Pre_Experiment_Spend']
Y = orders_pd['OrderValue']
X_mean = X.mean()

# Calculate Theta
covariance = np.cov(X,Y)[0,1]
variance_X = np.var(X,ddof=1)
theta = covariance / variance_X

# Apply CUPED adjustment
orders_pd['OrderValue_CUPED'] = Y - theta * (X-X_mean)

# Compare standard Errors before and after CUPED
se_original = orders_pd.groupby('ExperimentGroup')['OrderValue'].sem()
se_cuped = orders_pd.groupby('ExperimentGroup')['OrderValue_CUPED'].sem()

print("\n--- CUPED Variance Reduction ---")
print(f"Theta: {theta:.4f}")
print(f"Original Standard Error: Control={se_original['Control']:.2f}, Treatment={se_original['Treatment']:.2f}")
print(f"CUPED Standard Error:    Control={se_cuped['Control']:.2f}, Treatment={se_cuped['Treatment']:.2f}")
print(f"Variance Reduction: {(1 - (se_cuped['Control']/se_original['Control'])**2)*100:.1f}%")

"""# **Phase 4: User Segmentation & Predictive Analytics**

1. Behavioral Clustering (RFM + K-Means)
"""

# We calculate Recency, Frequency, and Monetary (RFM) metrics per user and apply K-Means clustering to group them into behavioral archetypes.

max_date = df_product_clean['OrderDate'].max()

rfm_df = (
    df_product_clean
    .group_by('Customer ID')
    .agg(
        ((max_date - pl.col('OrderDate').max()).dt.total_days()).alias('Recency'),
        pl.col('Invoice').n_unique().alias('Frequency'),
        pl.col('Revenue').sum().alias('Monetary')
    )
    .filter(pl.col('Monetary') > 0)
)

# Prepare data for Scikit-Learn
rfm_pd = rfm_df.to_pandas()
X_rfm = rfm_pd[['Recency','Frequency','Monetary']]

# Log-transform and Scale features to handle extreme retail outliers
X_scaled = StandardScaler().fit_transform(np.log1p(X_rfm))

# Train K-Means
kmeans = KMeans(n_clusters=4,random_state=42,n_init=10)
rfm_pd['Cluster'] = kmeans.fit_predict(X_scaled).astype(str)

# Map clusters to descriptive Product Archestypes based on means
cluster_summary = rfm_pd.groupby('Cluster')[['Recency','Frequency','Monetary']].mean()
print('Cluster Profiles:')
display(cluster_summary.round(1))

fig_user_segmentation = px.scatter_3d(
    rfm_pd,
    x='Recency',
    y='Frequency',
    z='Monetary',
    color='Cluster',
    opacity=0.7,
    title='3D Behavioral User Segmentation (RFM + K-Meand)',
    log_y=True,
    log_z=True
)

fig_user_segmentation.update_layout(margin=dict(l=0,r=0,b=0,t=40))
fig_user_segmentation.show()

"""2. Churn Prediction (Random Forest)

- Let's predict which customers will churn in the second half of the year based on their behavior in the first 90 days.
"""

# Split data into Observation Window (First 90 days) and Performance Window (Next 180 days)
start_date = df_product_clean['OrderDate'].min()
obs_end = start_date + pd.Timedelta(days=90)

obs_data = df_product_clean.filter(pl.col('OrderDate')<= obs_end)
perf_data = df_product_clean.filter(pl.col('OrderDate') > obs_end)

# Build feature from Observation Window
features = (
    obs_data
    .group_by('Customer ID')
    .agg(
        pl.col('Invoice').n_unique().alias('Obs_Orders'),
        pl.col('Revenue').sum().alias('Obs_Revenue'),
        pl.col('Quantity').sum().alias('Obs_Units'),
        ((obs_end - pl.col('OrderDate').max()).dt.total_days()).alias('Obs_Recency')
    )
)

# Identify who returned in the Performance Window (0= Churned, 1= Retained)
active_future = perf_data.select('Customer ID').unique().with_columns(pl.lit(0).alias('Churned'))
churn_dataset = (
    features
    .join(active_future, on='Customer ID',how='left')
    .with_columns(pl.col('Churned').fill_null(1)) # If null in future, they churned (=1)
).to_pandas()

# Train/Test Split
X = churn_dataset[['Obs_Orders','Obs_Revenue','Obs_Units','Obs_Recency']]
y = churn_dataset['Churned']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42)

# Train Classifier
clf = RandomForestClassifier(n_estimators=100,max_depth=5,random_state=42)
clf.fit(X_train,y_train)
preds = clf.predict_proba(X_test)[:, 1]

print("--- Churn Prediction Model Performance ---")
print(f"ROC-AUC Score: {roc_auc_score(y_test, preds):.3f}")
print("Feature Importances:", dict(zip(X.columns, clf.feature_importances_.round(3))))

"""**3. Customer Lifetime Value (LTV) Forecasting**
- We use simple linear regression to forecast 12-month LTV based on first-month spend.
"""

m1_revenue = (
    obs_data
    .group_by('Customer ID')
    .agg(pl.col('Revenue').sum().alias('Month_1_Spend'))
)

# Calculate Total 12-Month Revenue per User
total_revenue = (
    df_product_clean
    .group_by('Customer ID')
    .agg(pl.col('Revenue').sum().alias('Annual_LTV'))
)

ltv_df = m1_revenue.join(total_revenue, on='Customer ID').to_pandas()

# Fit Linear Regression Model
lr = LinearRegression()
lr.fit(ltv_df[['Month_1_Spend']], ltv_df['Annual_LTV'])

print(f"\n--- Simple LTV Forecast Model ---")
print(f"Formula: Predicted 12-Month LTV = £{lr.intercept_:.2f} + ({lr.coef_[0]:.2f} * Month_1_Spend)")

fig_regression = px.scatter(
    ltv_df,
    x='Month_1_Spend',
    y='Annual_LTV',
    opacity=0.5,
    trendline='ols',
    title = '30-Day Spend vs. 12-Month Actual LTV (£)',
    log_x=True,
    log_y=True,
    labels={'Month_1_Spend':'1st Month Spend','Annual_LTV':'Annual LTV'}
)

fig_regression.show()

"""# **Phase 5: Automating Repetitive Data Workflows**

Automated Rolling $z$-Score Anomaly Detection

- This script calculates daily revenue, evaluates a 14-day rolling window to compute a *z-score*, and automatically flags anomaly days where `z > 2.5`



```
z= xi - rolling / Orolling
```


"""

# Aggregate Daily Revenue
daily_rev = (
    df_product_clean
    .group_by('OrderDate')
    .agg(pl.col('Revenue').sum().alias('Daily_Revenue'))
    .sort('OrderDate')
).to_pandas()

# Calculate 14-day rolling mean and standard Deviation
daily_rev['Rolling_Mean'] = daily_rev['Daily_Revenue'].rolling(window=14,min_periods=7).mean()
daily_rev['Rolling_Std'] = daily_rev['Daily_Revenue'].rolling(window=14,min_periods=7).std()

#. Calcuate z-score and flag anomalies
daily_rev['Z_Score'] = (daily_rev['Daily_Revenue'] - daily_rev['Rolling_Mean']) / daily_rev['Rolling_Std']
daily_rev['Is_Anomaly'] = daily_rev['Z_Score'].abs() > 2.5

fig_std = px.line(
    daily_rev,
    x='OrderDate',
    y='Daily_Revenue',
    title='Automated Anomaly Detection (Rolling Z-Socre > 2.5)',
    labels={'Daily_Revenue': 'Daily Revenue','OrderDate':'Order Date'}
)
anomalies = daily_rev[daily_rev['Is_Anomaly']]
fig_std.add_trace(go.Scatter(
    x=anomalies['OrderDate'],
    y=anomalies['Daily_Revenue'],
    mode='markers',
    name='Anomalies',
    marker=dict(color='red',size=10,symbol='x')
))
fig_std.show()

print(f"Detected {len(anomalies)} anomaly days in the transaction logs.")