# -*- coding: utf-8 -*-
"""Product_Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xuqaXRJ93Vhu_kxYJSXGay7BNuXa-MzW
"""

import streamlit as st
import polars as pl
import pandas as pd
import plotly.express as px

import streamlit as st
import polars as pl
import pandas as pd
import plotly.express as px
import plotly.express.colors as px_colors

st.set_page_config(page_title='Product Analytics Suite',layout='wide')
st.title('🚀 Product Analytics Interactive Dashboard')
st.markdown('Powered by **Polars**, **Plotly**, and **Streamlit**')

@st.cache_data
def load_data():
  df_product = pl.read_csv(
      'online_retail - Year 2009-2010.csv',
      schema_overrides={'Invoice': pl.Utf8, 'Customer ID': pl.Utf8}
  )
  return (
      df_product.filter(pl.col('Customer ID').is_not_null())
      .filter(~pl.col('Invoice').str.starts_with('C'))
      .filter(pl.col('Quantity') > 0)
      .filter(pl.col('Price') > 0)
      .with_columns(
          pl.col("Customer ID").cast(pl.Int64).cast(pl.String).alias("CustomerID"),
          (pl.col('Quantity') * pl.col('Price')).alias('Revenue'),
          pl.col('InvoiceDate').str.strptime(pl.Datetime, format='%m/%d/%y %H:%M').alias('InvoiceDateTime'),
          pl.col('InvoiceDate').str.strptime(pl.Datetime, format='%m/%d/%y %H:%M').dt.strftime('%Y-%m').alias('YearMonth'),
          pl.col('InvoiceDate').str.strptime(pl.Datetime, format='%m/%d/%y %H:%M').dt.date().alias('OrderDate')
      )
  )

df_product_clean= load_data()

# Sidebar Filters
st.sidebar.header('Filter Controls')
selected_country = st.sidebar.multiselect(
     'Select Country',
    options=df_product_clean['Country'].unique().to_list(),
    default=['United Kingdom','Germany','France']
  )

filtered_product_df = df_product_clean.filter(pl.col('Country').is_in(selected_country))

# KPI Summary Cards
col1,col2,col3 = st.columns(3)
col1.metric('Total Revenue',f'£{filtered_product_df['Revenue'].sum():,.0f}')
col2.metric('Active Customers',f'{filtered_product_df['CustomerID'].n_unique():,}')
col3.metric('Total Orders',f'{filtered_product_df['Invoice'].n_unique():,}')

# Tabs for specific analytics workflows
tab1,tab2 = st.tabs(['📊 Revenue & Funnel Trends','🧬 User Behavioral Segments'])

with tab1:
  st.subheader('Monthly Revenue Trend')
  monthly = filtered_product_df.group_by('YearMonth').agg(pl.col('Revenue').sum()).sort('YearMonth')
  fig_monthly = px.bar(
      monthly.to_pandas(),
      x='YearMonth',
      y='Revenue',
      color_discrete_sequence=px_colors.sequential.Viridis
  )
  st.plotly_chart(fig_monthly,use_container_width=True)

with tab2:
  st.subheader('RFM Customer Segmentation Distribution')
  max_date = filtered_product_df['OrderDate'].max()
  rfm = (
      filtered_product_df.group_by('CustomerID')
      .agg(
          ((max_date - pl.col('OrderDate').max()).dt.total_days()).alias('Recency'),
          pl.col('Invoice').n_unique().alias('Frequency'),
          pl.col('Revenue').sum().alias('Monetary')
      )
  ).to_pandas()
  fig_rfm = px.scatter(
      rfm,
      x='Recency',
      y='Monetary',
      size='Frequency',
      log_y=True,
      title='Recency vs. Monetary Value (Size = Frequency)'
  )
  st.plotly_chart(fig_rfm, use_container_width=True)